### ISSUE TITLE
EEPROM Driver

### ISSUE THREAD

**Issue by ztnel** [dronectl/raptor#6]
# Description
Implement a simple EEPROM driver for the ATMEGA328p. The EEPROM will be used for storing network and device configuration settings. The datasheet for the 328p can be referenced here:  https://ww1.microchip.com/downloads/en/DeviceDoc/Atmel-7810-Automotive-Microcontrollers-ATmega328P_Datasheet.pdf

I have written a simple EEPROM driver in the past for atmega MCUs which can be referenced [here](https://github.com/ztnel/ucl/blob/master/src/drivers/eeprom.c) .  The read and write implementations should be the same similar. Check that the register names are qualified by `avr-gcc` for the 328p.

To verify correct read and write operation over the entire range of the EEPROM you can write a simple test function to log the result of the read and write. I have also written such a function and can be found [here](https://github.com/ztnel/ucl/blob/master/src/tests.c)

**Comment by ztnel** [comment]
Section 7.4 contains details about EEPROM I/O.

**Comment by BrandonLucasZhu** [comment]
Closing issue as it's tagged as won't fix.
